### ISSUE TITLE
Need a demo

### ISSUE THREAD

**Issue by helele90** [meituan/EasyReact#19]
Need a demo.
demo is a empty viewController.

**Comment by WilliamZang** [comment]
Well, we will create a feature. But EasyReact is only a base library, what does the GUI demo look like ?

**Comment by kekeYezi** [comment]
For example, some scenes commonly used in projects.

**Comment by helele90** [comment]
I thought there would be a simple demo use mvvm architecture.
like rxswift, RAC.

**Comment by haotianling** [comment]
demo 都没有，用起来不方便

**Comment by WilliamZang** [comment]
We will create a demo soon. You can see test cases now. Those test cases include all features.

**Comment by WilliamZang** [comment]
We will create a demo soon. You can see test cases now. Those test cases include all features.

**Comment by OpenFeyn** [comment]
请大伙使用RAC

**Comment by OpenFeyn** [comment]
1、在国内，美团研究RAC的文章最多，功力也相当深刻；
2、但始祖RAC，在readme中都是先写用法及使用场景，再写其他。里头居然是一个test case，目的是什么？给人一种这个库开源仅仅为了告诉世人这个库很牛的感觉，开源也不是什么因为开源精神的指引。

**Comment by Liuzhenjie123** [comment]
有没有交流群之类的

**Comment by WilliamZang** [comment]
@Liuzhenjie123 可以搞一个，我更新下中文README

**Comment by WilliamZang** [comment]
@Liuzhenjie123 已经更新中文README，欢迎交流

![微信交流群](https://github.com/meituan/EasyReact/blob/master/images/wechat.jpeg)

**Comment by loulou886** [comment]
二维码失效了，请更新一下
