### ISSUE TITLE
主线程同步问题

### ISSUE THREAD

**Issue by jkqs** [meituan/EasyReact#26]
主线程开启一个同步线程，并不会真正去新开线程，而是会优化到当前主线程，所以文档中如下写法，都是在主线程执行的，不会有什么问题：
dispatch_sync(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
  [NSThread currentThread].threadDictionary[@"flag"] = @"这是某个子线程";//此处应该为主线程
  //UI操作
});

**Comment by WilliamZang** [comment]
Fixed in PR #27
