### ISSUE TITLE
syncWith:transform:revert API Error

### ISSUE THREAD

**Issue by zhudaye12138** [meituan/EasyReact#33]
When I syncWith   EZRNode<NSNumber *>  and  EZRNode<NSString *>  ,there will be a mistake
   
```
    EZRMutableNode<NSNumber *> *nodeA = [EZRMutableNode new];
    EZRMutableNode<NSString *> *nodeB = [EZRMutableNode new];
    
    [nodeA syncWith:nodeB transform:^id _Nonnull(NSNumber * _Nonnull source) {
        NSLog(@"class is %@",[source class]);    // source is not NSNumber but  __NSCFConstantString
         return @"9";
    } revert:^NSNumber * _Nonnull(id  _Nonnull target) {
         return @2;
    }];
```

The current API is

`- (id<EZRCancelable>)syncWith:(EZRNode *)othEZRNode transform:(id (^)(T source))transform revert:(T (^)(id target))revert;`

Maybe this way is right

`- (id<EZRCancelable>)syncWith:(EZRNode<T> *)othEZRNode transform:(T (^)(T source))transform revert:(T (^)(T target))revert;`

**Comment by WilliamZang** [comment]
Oops, `othEZRNode` is a typo error. You can PR and fix it.

Current API defines right. Objective-C only has class generics but not method generics. 

`- (id<EZRCancelable>)syncWith:(EZRNode<T> *)othEZRNode transform:(T (^)(T source))transform revert:(T (^)(T target))revert;` only can sync `EZRNode<T> *` with `EZRNode<T> *` which are same type.

But I saw the source code, implementation is wrong. Thanks for telling us! It's great!

You can push a PR to fix it. Don't forget change [test case: EZRNode+Operation.m](https://github.com/meituan/EasyReact/blob/2.2.1/Example/Tests/EZRNode%2BOperation.m#L515), different type convert is better.

**Comment by zhudaye12138** [comment]
OK, I'm done @WilliamZang

**Comment by ValiantCat** [comment]
Good job!
Would you like to join Beijing Sankuai Online Technology Co. (MeiTuan)

**Comment by zhudaye12138** [comment]
I will have an interview in chengdu MeiTuan  next week   ：） @ValiantCat

**Comment by ValiantCat** [comment]
@WilliamZang

**Comment by WilliamZang** [comment]
@zhudaye12138 Why not Beijing?
