### ISSUE TITLE
方法缺失

### ISSUE THREAD

**Issue by lcl2539** [meituan/EasyReact#38]
在文档中明确出现的 withSelector 方法，在框架中并不存在，请问这是什么原因？

**Comment by WilliamZang** [comment]
是指这个？[EZRListenContext.h#L51](https://github.com/meituan/EasyReact/blob/master/EasyReact/Classes/Core/EZRListenContext.h#L51)

**Comment by lcl2539** [comment]
这里是存在的
但是我是使用Pod直接导入到项目中的
EZRListenContext.h文件中并不存在这个方法

**Comment by WilliamZang** [comment]
因为是2.3.0版本的，还没有发布

着急可以先用 pod 'EasyReact', git: 'https://github.com/meituan/EasyReact.git', branch: 'master' 来引入最新版

**Comment by lcl2539** [comment]
好的，谢谢
