### ISSUE TITLE
[!] Unable to find a specification for `EasyFoundation (~> 1.0.0)` depended upon by `EasyReact`

### ISSUE THREAD

**Issue by ptlCoder** [meituan/EasyReact#39]
[!] Unable to find a specification for `EasyFoundation (~> 1.0.0)` depended upon by `EasyReact`

**Comment by ienho** [comment]
需要更新master库，EasyReact依赖的几个基础库 都是最近加入到cocoapods中的

**Comment by face2d** [comment]
try
```
pod repo update
```

**Comment by WilliamZang** [comment]
@ptlCoder I've closed this issue. You can reopen it if you still have problem.
