### ISSUE TITLE
EZ_TUPLE_CLASSES_DEF

### ISSUE THREAD

**Issue by StarShare** [meituan/EasyReact#45]
### Context and Description

error: Cannot declare variable inside @interface or @protocol

### Environment Details

* EasyReact version: newest
* iOS version: 11.4
* Xcode version:9.4
* Other informations:

**Comment by WilliamZang** [comment]
Could you give me some detail like example code?

**Comment by StarShare** [comment]
只要我 import EasyReact 就会报错～

**Comment by StarShare** [comment]
`/Users/Documents/Pods/Headers/Public/EasyTuple/EZTupleSubClasses.h:11:1: error: expected type parameter name
EZ_TUPLE_CLASSES_DEF`

`/Users/Documents/Pods/Headers/Public/EasyTuple/EZTupleSubClasses.h:11:1: error: type name requires a specifier or qualifier
`

`/Users/Documents/Pods/Headers/Public/EasyTuple/EZTupleSubClasses.h:11:1: error: expected member name or ';' after declaration specifiers`

`/Users/Documents/Pods/Headers/Public/EasyTuple/EZTupleSubClasses.h:11:1: error: expected ')'`

类似这种错误很多，编译不起来。

![_f7ab7bbb-9cff-465e-b5b3-1b7b47a86529](https://user-images.githubusercontent.com/32382044/43942278-e7f4cbcc-9ca9-11e8-95b0-afdf0c2a0441.png)

**Comment by WilliamZang** [comment]
工程方便提供一下么？

**Comment by iURWang** [comment]
项目不太方便…，我项目里也有rac，不知道会不会有影响或者冲突什么的
