### ISSUE TITLE
EasyReact中如何去监听一个控件的状态呢，比如UITextField的输入变化

### ISSUE THREAD

**Issue by lizelu** [meituan/EasyReact#52]
有没有直接获取UITextField的Node的方法，然后对这个Node进行监听？

**Comment by lizelu** [comment]
看了一下源码，其中貌似没有UIKit相关的Extension，请问什么时候会对UI进行扩充呢

**Comment by ValiantCat** [comment]
EasyReact 是一个非常纯粹的跨平台项目  iOS / mac OS 
UIKit扩展在MVVM框架里 后期会逐渐开源

**Comment by lizelu** [comment]
![ezr](https://user-images.githubusercontent.com/5105794/44562408-0969f880-a78c-11e8-9f18-8bbb2c6f06b1.gif)
`    __weak typeof(self) weak_self = self;
    [[self.myTextField.node listenedBy:self] withBlock:^(NSString *text) {
        weak_self.logLabel.text = text;
    }];
`
这边基于EZRNode简单的做了个Category，可以实现监听输入变化~

**Comment by WilliamZang** [comment]
可以参考下 https://github.com/meituan/EasyReact/blob/feature/demo/Example/EasyReact/Libs/UITextField%2BEZR_Extension.m

**Comment by lizelu** [comment]
赞~👍👍基于EZRNode还是比较好扩充的~

**Comment by WilliamZang** [comment]
双向绑定用一个防止回声的标志就可以了

**Comment by WilliamZang** [comment]
@lizelu 没有问题的话，ISSUE我关闭了啊
