### ISSUE TITLE
监听节点值

### ISSUE THREAD

**Issue by Wu123345** [meituan/EasyReact#56]
EZRMutableNode<NSNumber *> *node = [EZRMutableNode value:@1];
NSObject *listener = [NSObject new];
[[node listenedBy:listener] withBlock:^(NSNumber *next) {
  NSLog(@"下一个值是 %@", next);
}];

node.value = @2;
[node clean];
node.value = @3;
listener = nil;
node.value = @4;
打印是 1，2，3，4  listener = nil ;无效 需要 node = nil

**Comment by WilliamZang** [comment]
This should be a bug. Thank you! We will fix it soon.
