### ISSUE TITLE
为什么用模拟器跑benchmark而不是真机？

### ISSUE THREAD

**Issue by linlinyao1** [meituan/EasyReact#6]
用模拟器完全无法反映真实性能

**Comment by WilliamZang** [comment]
多谢反馈，我们会马上改用真机进行benchmark。之前因为模拟器比较方便所以疏忽了，以后我们会统一使用真机来进行。

**Comment by WilliamZang** [comment]
已经在 PR #7 改为真机了，稍后该 PR 合并后会自动关闭该 ISSUE，非常感谢您的反馈。我们会做得更好
