### ISSUE TITLE
 Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules

### ISSUE THREAD

**Issue by mrdaios** [meituan/EasyReact#68]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/2328496/48354333-665eb600-e6cc-11e8-8208-780ff90bc413.png">

**Comment by mrdaios** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/2328496/48354758-7034e900-e6cd-11e8-8f7c-70ffd2d489c3.png">

**Comment by WilliamZang** [comment]
Sorry about this. `@import` can't be support within Objective-C++ or C++. So we will use `#import` instead of `@import` in next release. Before we fix it you can fix all `@import` in your fork.

**Comment by mrdaios** [comment]
谢谢。

**Comment by huntingcat** [comment]
这个问题你是怎么解决的那？我这老是编译不通过

**Comment by mrdaios** [comment]
@huntingcat 我是修改了mutable为其他字段，你可以问问。

**Comment by WilliamZang** [comment]
好像是新的xcode把mutable变为关键字了。
哎，名字起得不好
