### ISSUE TITLE
Create nodes for UIControl

### ISSUE THREAD

**Issue by Magic-Unique** [meituan/EasyReact#69]
How to create a category for UIControl, and create nodes for control event?

Expect:

```objc
[[[btn ezr_nodeForControlEvents:UIControlEventTouchUpInside] listenBy:self] withBlock:...]
```

In RAC, the `value` is UIControl, but it will cycle-retain if node's value is UIControl.
And if a new node link to this node, it will get a new value (UIControl) for default without any user-action.

**Comment by WilliamZang** [comment]
There are 2 problems in your case.
One of these is UIControl's cycle-retain . To resolve it has 2 solutions. You can use EZSWeakReference to wrapper UIControl, or you can set another value not include UIControl. By the way, we have a plan to create a weak-store node, see #58.
Another of these is alway get a new  value when link or listen. To resolve it just use `skip:1`.

Thank you for trying EasyReact.

**Comment by Magic-Unique** [comment]
Ok, thanks. waiting for your MVVM project.
